name: petdoctor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase suite
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore:
  firebase_app_check: ^0.0.6+7
  firebase_messaging: ^11.2.11
  firebase_storage: ^10.2.9
  firebase_analytics: ^9.1.2
  firebase_remote_config: ^2.0.1
  geoflutterfire: ^3.0.3

 # stacked
  stacked: ^2.3.0
  stacked_services: ^0.8.17
  logger: ^1.1.0

 # in-house libraries
  pawcastle_phoneauth:
    git:
      url: https://github.com/MovingMelody/pawcastle-phoneauth.git
      ref: main

  pawcastle_designsystem:
    git:
      url: https://github.com/MovingMelody/pawcastle-designsystem-flutter.git
      ref: main

  pawcastle_datamodels:
    git:
      url: https://github.com/MovingMelody/pawcastle-datamodels.git
      ref: main

  dotted_border: ^2.0.0+2
  awesome_notifications: ^0.6.19
  agora_rtc_engine: ^5.2.0
  lottie: ^1.3.0

  flutter_dotenv: ^5.0.2
  flutter_ringtone_player: ^3.1.1
  fluttertoast: ^8.0.8

  image_picker: 
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.10
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.8
  
  # old data models
  stacked_generator: ^0.6.0

  mockito:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/ms-regular.ttf
          weight: 400
        - asset: assets/fonts/ms-smbold.ttf
          weight: 600
        - asset: assets/fonts/ms-bold.ttf
          weight: 700
    
    - family: IconPack
      fonts:
        - asset: assets/fonts/IconPack.ttf